name: first workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
        python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
        python -m pip install --upgrade pip
        python -m pip install behave
        python -m pip install playwright
        
     - name: Amazon tests
       run: |
         ./testing_assignment_using_pom/features/amazon.feature
        
     - name: Company tests 
       run: |
         ./testing_assignment_using_pom/features/company.feature

     - name: Map tests 
       run: |
         ./testing_assignment_using_pom/features/google_map.feature
         
     
