name: first workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
        python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
        python -m pip install --upgrade pip
        python -m pip install behave
        python -m pip install playwright
        
     - name: Amazon tests
       run: |
         git update-index --chmod=+x ./testing_assignment_using_pom/features/amazon.feature
        
     - name: Company tests 
       run: |
         git update-index --chmod=+x ./testing_assignment_using_pom/features/company.feature

     - name: Map tests 
       run: |
         git update-index --chmod=+x ./testing_assignment_using_pom/features/google_map.feature

     - name: Get Allure history # Step to retrieve Allure history
       uses: actions/checkout@v3
       if: always() # Execute even if previous steps fail
       continue-on-error: true # Continue execution even if the step fails
       with:
          ref: gh-pages # Specify the branch to retrieve Allure history from
          path: gh-pages # Set the destination path for Allure history

 

     - name: Allure report action # Step to generate Allure report
       uses: simple-elf/allure-report-action@master
       if: always() # Execute even if previous steps fail
       with:
          allure_results: ${{ vars.ALLURE_RESULTS_PATH }} # Specify the directory containing Allure results
          allure_history: allure-history # Specify the directory to store Allure history
          keep_reports: 5 # Specify the number of previous reports to keep

 

     - name: Deploy Allure report to GitHub Pages # Step to deploy Allure report to GitHub Pages
       if: always() # Execute even if previous steps fail
       uses: peaceiris/actions-gh-pages@v3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Provide the GitHub token for authentication
          publish_branch: gh-pages # Specify the branch to publish the report to
          publish_dir: allure-history # Specify the directory containing the report
     
